#!/bin/bash
set -e

if ! dpkg -l | grep linux-image | grep -v dbg | grep tw5864 >& /dev/null
then
	echo "Detected that there's no more linux-image packages providing tw5864. Removing custom modules loading hints"
	rm -v /etc/modules-load.d/solo6x10.conf
	rm -v /etc/modules-load.d/tw5864.conf
	rm -v /etc/modprobe.d/blacklist-solo6x10_edge.conf
fi
