CREATE TABLE GlobalSettings (
	parameter varchar(60) PRIMARY KEY NOT NULL,
	value varchar(255)
);

INSERT INTO GlobalSettings VALUES ('G_DVR_NAME', 'Bluecherry DVR v2');
INSERT INTO GlobalSettings VALUES ('G_DVR_EMAIL', 'root@localhost');
INSERT INTO GlobalSettings VALUES ('G_DVR_MEDIA_STORE', '/var/lib/bluecherry/recordings');
INSERT INTO GlobalSettings VALUES ('G_DEV_SCED', 'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC');
INSERT INTO GlobalSettings VALUES ('G_DEV_NOTES', '');

CREATE TABLE Storage (
	priority integer PRIMARY KEY NOT NULL,
	path varchar(512) NOT NULL,
	max_thresh integer NOT NULL,
	min_thresh integer NOT NULL,
	UNIQUE (path)
);

INSERT INTO Storage VALUES (1, '/var/lib/bluecherry/recordings', 95, 90);
