CREATE TABLE 'deviceSchedule' (
	'id' CHAR(8) PRIMARY KEY,
	'schedule' CHAR(168) NOT NULL DEFAULT 'MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM',
	'override_global' BOOLEAN NOT NULL DEFAULT '0'
);
