CREATE TABLE GlobalSettings (
	parameter varchar(60) PRIMARY KEY NOT NULL,
	value varchar(255)
);

INSERT INTO 'GlobalSettings' VALUES ('G_DVR_NAME', 'Bluecherry DVR v2');
INSERT INTO 'GlobalSettings' VALUES ('G_DVR_EMAIL', 'root@localhost');
INSERT INTO 'GlobalSettings' VALUES ('G_DVR_MEDIA_STORE', '/var/lib/bluecherry/recordings');
INSERT INTO 'GlobalSettings' VALUES ('G_DEV_SCED', 'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC');
INSERT INTO 'GlobalSettings' VALUES ('4', 'G_DEV_NOTES', '');
