#!/bin/sh

set -e

case "$1" in
	upgrade)
		echo "UPGRADES WILL NOT WORK!!"
		echo "Please 'dpkg -P bluecherry' before installing this new package"
		exit 1
		;;
	install)
		if ! id bluecherry > /dev/null 2>&1; then
			useradd -c "Bluecherry DVR" -d /var/lib/bluecherry \
				-G audio,video -M -U -r bluecherry
			# And www-data will need it too
			usermod -a -G video,audio,bluecherry www-data
		fi
		stop bluecherry || true
		;;
esac

#DEBHELPER#
