#!/bin/sh

set -e

sql="/usr/share/doc/bluecherry/sqlite-base.sql.gz"
dbdir="/var/lib/bluecherry"
db="$dbdir/bluecherry.sqlite"

case "$1" in
	configure|reconfigure)
		if [ -f "$sql" -a ! -f "$db" ]; then
			test -d $dbdir || mkdir $dbdir
			zcat "$sql" | sqlite3 "$db"
			chmod 660 "$db"
			chown bluecherry:bluecherry "$dbdir" -R
		fi
		chown bluecherry:bluecherry /etc/bluecherry.conf
		# Apache modules
		a2ensite bluecherry
		a2enmod ssl
		a2enmod php5
		;;
esac

#DEBHELPER#
