#!/bin/sh

set -e

sql="/usr/share/doc/bluecherrydvr/sqlite-base.sql.gz"
dbdir="/var/lib/bluecherry"
db="$dbdir/bluecherry.sqlite"

case "$1" in
	configure|reconfigure)
		if [ -f "$sql" -a ! -f "$db" ]; then
			test -d $dbdir || mkdir $dbdir
			zcat "$sql" | sqlite3 "$db"
			chmod 640 "$db"
			chown bcdvr:www-data "$dbdir" -R
		fi
		chown bcdvr:www-data /etc/bluecherry.conf
		;;
esac

#DEBHELPER#
