#!/bin/bash

echo '
CREATE TABLE `webhooks` (
	`id` SMALLINT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
	`label` VARCHAR(50) NOT NULL,
	`url` VARCHAR(255) NOT NULL,
	`events` VARCHAR(255) NULL DEFAULT NULL,
	`cameras` VARCHAR(255) NULL DEFAULT NULL,
	`status` TINYINT(4) NOT NULL DEFAULT '0',
	`last_update` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
' | mysql -h"$host" -D"$dbname" -u"$user" -p"$password"
