/* xmlrpc_amconfig.h.  Generated by configure.  */
/* xmlrpc_amconfig.h is generated by 'configure' from the template
   xmlrpc_amconfig.h.in, by virtue of the AM_CONFIG_HEADER() macro in
   configure.in.

   In the future, we plan to eliminate this file, because it is a special
   tool that requires extra learning.  Instead, we will just put logic
   directly in configure.in like that for wchar.h, etc.
*/

/* The following are related to AC_CHECK_FUNCS macro calls in
   configure.in
*/

#define HAVE_SETGROUPS 1
#define HAVE_ASPRINTF 1
#define HAVE_SETENV 1
#define HAVE_PSELECT 1
#define HAVE_WCSNCMP 1
#define HAVE_GETTIMEOFDAY 1
#define HAVE_LOCALTIME_R 1
#define HAVE_GMTIME_R 1
#define HAVE_STRCASECMP 1
/* #undef HAVE_STRICMP */
/* #undef HAVE__STRICMP */
#define HAVE_STRTOLL 1
#define HAVE_STRTOQ 1
/* #undef HAVE___STRTOLL */
#define HAVE_STRTOULL 1
#define HAVE_STRTOUQ 1
/* #undef HAVE___STRTOULL */


/* Define if you have the socket library (-lsocket).  */
/* #undef HAVE_LIBSOCKET */

/* Name of package */
#define PACKAGE "xmlrpc-c"
