name: Publish Docker image
on:
  push:
    branches: [ "dev", "master" ]
  pull_request_target:
    types: [opened, reopened, synchronize, ready_for_review]
    branches: [ "dev", "master" ]
    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

jobs: 
  mysql57:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false && !contains(github.event.pull_request.labels.*.name, 'WIP')
    steps:
      - uses: actions/checkout@v2
      - name: Shutdown existing MySQL
        run: sudo service mysql stop

  push_to_registries:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false && !contains(github.event.pull_request.labels.*.name, 'WIP')
    permissions:
      packages: write
      contents: read
    steps:
      - name: Set up MySQL
        uses: cweinberger/github-actions-mysql@main
        with:
          version: 5.7
          hostPort: 3306
          containerPort: 3306
          rootPassword: root
          user: TestUser
          password: TestPassword
          database: TestDatabase
          characterSet: utf8mb4
          collation: utf8mb4_general_ci
          sqlMode: NO_ENGINE_SUBSTITUTION
 
      - name: Print running docker containers
        run: docker ps
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Get branch name
        run: echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
      - name: Identify git repo path
        run: ls $GITHUB_WORKSPACE && ls -l /home/runner/work/
      - name: Wait for mysql
        run: sleep 15
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2      
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: bluecherrydvr/bluecherry
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v4     
        with:
            #working-directory: server/
            context: ./actions
            dockerfile: ./actions/Dockerfile            
#            context: "{{defaultContext}}:actions"
            push: true
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}
