name: Publish Docker image
on:
  push:
    branches: [ "dev", "master" ]
    tags:
      - v*
  pull_request_target:
    types: [opened, reopened, synchronize, ready_for_review]
    branches: [ "dev", "master" ]
  workflow_dispatch:

jobs: 
  push_to_registries:
    runs-on: ubuntu-latest
    if: (github.event_name == 'workflow_dispatch') || (github.event.pull_request.draft == false && !contains(github.event.pull_request.labels.*.name, 'WIP'))
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Get branch name
        run: echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: bluecherrydvr/bluecherry
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
            context: ./actions
            dockerfile: ./actions/Dockerfile
            push: true
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}
