name: Build & Push Bluecherry (from .deb)

on:
  push:
    branches: [ "dev-ci", "master" ]
    tags:     [ "v*" ]
  workflow_dispatch:
    inputs:
      deb_url:
        description: "Override .deb URL (optional)"
        required: false
      image_tag:
        description: "Override image tag (optional)"
        required: false

concurrency:
  group: docker-build
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write

    env:
      DEFAULT_DEB_URL: http://dl.bluecherrydvr.com/pool/noble/bluecherry_3.1.14_amd64.deb
      DEFAULT_IMAGE:   bluecherrydvr/bluecherry

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Decide inputs (URL & tag)
        id: decide
        run: |
          set -euo pipefail
          URL="${{ inputs.deb_url || env.DEFAULT_DEB_URL }}"
          # Tag priority: workflow input > Git tag (strip 'v') > branch > 'latest' for master/main
          if [ -n "${{ inputs.image_tag }}" ]; then
            TAG="${{ inputs.image_tag }}"
          elif [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
            TAG="${GITHUB_REF_NAME#v}"     # v3.1.14 -> 3.1.14
          elif [[ "${GITHUB_REF_NAME}" =~ ^(master|main)$ ]]; then
            TAG="latest"
          else
            TAG="${GITHUB_REF_NAME}"
          fi
          echo "deb_url=$URL"   >> "$GITHUB_OUTPUT"
          echo "image_tag=$TAG" >> "$GITHUB_OUTPUT"
          echo "Using .deb: $URL"
          echo "Image tag:  $TAG"

      - name: Compute SHA256 of .deb (optional, for verification)
        id: sha
        run: |
          set -euo pipefail
          curl -fsSL "${{ steps.decide.outputs.deb_url }}" -o /tmp/bluecherry.deb
          SHA="$(sha256sum /tmp/bluecherry.deb | awk '{print $1}')"
          echo "sha=$SHA" >> "$GITHUB_OUTPUT"
          echo "SHA256: $SHA"

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push (plain logs)
        uses: docker/build-push-action@v6
        with:
          context: .
          # Adjust if your Dockerfile lives somewhere else
          file: ./actions/Dockerfile
          push: true
          tags: |
            ${{ env.DEFAULT_IMAGE }}:${{ steps.decide.outputs.image_tag }}
          build-args: |
            INSTALL_METHOD=deb
            BLUECHERRY_DEB_URL=${{ steps.decide.outputs.deb_url }}
            BLUECHERRY_DEB_SHA256=${{ steps.sha.outputs.sha }}
          cache-from: type=registry,ref=${{ env.DEFAULT_IMAGE }}:buildcache
          cache-to:   type=registry,ref=${{ env.DEFAULT_IMAGE }}:buildcache,mode=max
          provenance: false
          sbom: false
          outputs: type=image,name=${{ env.DEFAULT_IMAGE }},push-by-digest=true,name-canonical=true
          # show full Dockerfile logs so we can see each RUN
          build-args-from-env: false
          no-cache: false
          pull: true
          # Display detailed BuildKit logs:
          # (v6 uses global logging; we can enforce plain output via env)
        env:
          BUILDKIT_PROGRESS: plain
